//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanGuard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScanGuard.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re dedicated to making the digital world safer with powerful tools to scan and secure websites and files from vulnerabilities..
        /// </summary>
        public static string About_text {
            get {
                return ResourceManager.GetString("About_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ScanGuard.
        /// </summary>
        public static string AboutScanGuard {
            get {
                return ResourceManager.GetString("AboutScanGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        public static string Accessibility {
            get {
                return ResourceManager.GetString("Accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cybersecurity for everyone, everywhere..
        /// </summary>
        public static string AccessibilityText {
            get {
                return ResourceManager.GetString("AccessibilityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to community forums.
        /// </summary>
        public static string AccessToCommunity {
            get {
                return ResourceManager.GetString("AccessToCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced analytics and detailed reports.
        /// </summary>
        public static string AdvancedAnalytics {
            get {
                return ResourceManager.GetString("AdvancedAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Scanning.
        /// </summary>
        public static string AdvancedScanning {
            get {
                return ResourceManager.GetString("AdvancedScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All-in-one solution for your digital security..
        /// </summary>
        public static string AllInOne {
            get {
                return ResourceManager.GetString("AllInOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzed.
        /// </summary>
        public static string Analyzed {
            get {
                return ResourceManager.GetString("Analyzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API access for integration with your tools.
        /// </summary>
        public static string APIAccess {
            get {
                return ResourceManager.GetString("APIAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic support via email (response within 48 hours).
        /// </summary>
        public static string BasicSupport {
            get {
                return ResourceManager.GetString("BasicSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ChangePassword_ButtonCancel {
            get {
                return ResourceManager.GetString("ChangePassword_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ChangePassword_ButtonUpdate {
            get {
                return ResourceManager.GetString("ChangePassword_ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a new secure password..
        /// </summary>
        public static string ChangePassword_Description {
            get {
                return ResourceManager.GetString("ChangePassword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ChangePassword_LabelConfirmPassword {
            get {
                return ResourceManager.GetString("ChangePassword_LabelConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string ChangePassword_LabelCurrentPassword {
            get {
                return ResourceManager.GetString("ChangePassword_LabelCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string ChangePassword_LabelNewPassword {
            get {
                return ResourceManager.GetString("ChangePassword_LabelNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ChangePassword_PlaceholderConfirmPassword {
            get {
                return ResourceManager.GetString("ChangePassword_PlaceholderConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string ChangePassword_PlaceholderCurrentPassword {
            get {
                return ResourceManager.GetString("ChangePassword_PlaceholderCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string ChangePassword_PlaceholderNewPassword {
            get {
                return ResourceManager.GetString("ChangePassword_PlaceholderNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword_SectionTitle {
            get {
                return ResourceManager.GetString("ChangePassword_SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword_Title {
            get {
                return ResourceManager.GetString("ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI-Powered.
        /// </summary>
        public static string ChooseAI {
            get {
                return ResourceManager.GetString("ChooseAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart tech for smarter detection..
        /// </summary>
        public static string ChooseAIText {
            get {
                return ResourceManager.GetString("ChooseAIText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost-Effective.
        /// </summary>
        public static string ChooseCost {
            get {
                return ResourceManager.GetString("ChooseCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium security at fair prices..
        /// </summary>
        public static string ChooseCostText {
            get {
                return ResourceManager.GetString("ChooseCostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Scans.
        /// </summary>
        public static string ChooseFast {
            get {
                return ResourceManager.GetString("ChooseFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get results in seconds, not hours..
        /// </summary>
        public static string ChooseFastText {
            get {
                return ResourceManager.GetString("ChooseFastText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string ChooseSupport {
            get {
                return ResourceManager.GetString("ChooseSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help whenever you need it..
        /// </summary>
        public static string ChooseSupportText {
            get {
                return ResourceManager.GetString("ChooseSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients Protected.
        /// </summary>
        public static string ClientsProtected {
            get {
                return ResourceManager.GetString("ClientsProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehensive Protection.
        /// </summary>
        public static string ComprehensiveProtection {
            get {
                return ResourceManager.GetString("ComprehensiveProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Error.
        /// </summary>
        public static string ConfirmEmail_ErrorTitle {
            get {
                return ResourceManager.GetString("ConfirmEmail_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Home.
        /// </summary>
        public static string ConfirmEmail_LinkHome {
            get {
                return ResourceManager.GetString("ConfirmEmail_LinkHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to Login.
        /// </summary>
        public static string ConfirmEmail_LinkLogin {
            get {
                return ResourceManager.GetString("ConfirmEmail_LinkLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Secured.
        /// </summary>
        public static string ConfirmEmail_SecurityBadge {
            get {
                return ResourceManager.GetString("ConfirmEmail_SecurityBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your first line of defense in the digital world.
        /// </summary>
        public static string ConfirmEmail_Slogan {
            get {
                return ResourceManager.GetString("ConfirmEmail_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmed!.
        /// </summary>
        public static string ConfirmEmail_SuccessTitle {
            get {
                return ResourceManager.GetString("ConfirmEmail_SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email.
        /// </summary>
        public static string ConfirmEmail_Title {
            get {
                return ResourceManager.GetString("ConfirmEmail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us for updates and tips on staying secure online..
        /// </summary>
        public static string ConnectText {
            get {
                return ResourceManager.GetString("ConnectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with ScanGuard.
        /// </summary>
        public static string ConnectwithScanGuard {
            get {
                return ResourceManager.GetString("ConnectwithScanGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom scan schedules and automation.
        /// </summary>
        public static string CustomScan {
            get {
                return ResourceManager.GetString("CustomScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected threat on.
        /// </summary>
        public static string DetectedThreatOn {
            get {
                return ResourceManager.GetString("DetectedThreatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital.
        /// </summary>
        public static string Digital {
            get {
                return ResourceManager.GetString("Digital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email։.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URL to Scan.
        /// </summary>
        public static string EnterURLtoScan {
            get {
                return ResourceManager.GetString("EnterURLtoScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essential scanning for websites and files.
        /// </summary>
        public static string Essential {
            get {
                return ResourceManager.GetString("Essential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore advanced tools to secure your digital world..
        /// </summary>
        public static string ExploreAdvanced {
            get {
                return ResourceManager.GetString("ExploreAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Hash.
        /// </summary>
        public static string FileHash {
            get {
                return ResourceManager.GetString("FileHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the history of your scanned files and their security details.
        /// </summary>
        public static string FileHistoryText {
            get {
                return ResourceManager.GetString("FileHistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files Analyzed.
        /// </summary>
        public static string FilesAnalyzed {
            get {
                return ResourceManager.GetString("FilesAnalyzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan File.
        /// </summary>
        public static string FileScanButton {
            get {
                return ResourceManager.GetString("FileScanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Scan History.
        /// </summary>
        public static string FileScanHistory {
            get {
                return ResourceManager.GetString("FileScanHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Scanner.
        /// </summary>
        public static string FileScanner {
            get {
                return ResourceManager.GetString("FileScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your files to check for malware, vulnerabilities, and security threats with ScanGuard’s advanced scanning technology..
        /// </summary>
        public static string FileScannerText {
            get {
                return ResourceManager.GetString("FileScannerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File for Scanning.
        /// </summary>
        public static string FileUpload {
            get {
                return ResourceManager.GetString("FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start scanning now.
        /// </summary>
        public static string FutureStartScanningNow {
            get {
                return ResourceManager.GetString("FutureStartScanningNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join ScanGuard to protect your websites and files with confidence..
        /// </summary>
        public static string FutureText {
            get {
                return ResourceManager.GetString("FutureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in Touch.
        /// </summary>
        public static string GetinTouch {
            get {
                return ResourceManager.GetString("GetinTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Dashboard.
        /// </summary>
        public static string GoToDashboard {
            get {
                return ResourceManager.GetString("GoToDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guard.
        /// </summary>
        public static string Guard {
            get {
                return ResourceManager.GetString("Guard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy Users.
        /// </summary>
        public static string HappyUsers {
            get {
                return ResourceManager.GetString("HappyUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze.
        /// </summary>
        public static string History_ButtonAnalyze {
            get {
                return ResourceManager.GetString("History_ButtonAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string History_ButtonRemove {
            get {
                return ResourceManager.GetString("History_ButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string History_ColumnActions {
            get {
                return ResourceManager.GetString("History_ColumnActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Date.
        /// </summary>
        public static string History_ColumnScanDate {
            get {
                return ResourceManager.GetString("History_ColumnScanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerability Count.
        /// </summary>
        public static string History_ColumnVulnerabilityCount {
            get {
                return ResourceManager.GetString("History_ColumnVulnerabilityCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerability Type.
        /// </summary>
        public static string History_ColumnVulnerabilityType {
            get {
                return ResourceManager.GetString("History_ColumnVulnerabilityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website URL.
        /// </summary>
        public static string History_ColumnWebsiteURL {
            get {
                return ResourceManager.GetString("History_ColumnWebsiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load analysis.
        /// </summary>
        public static string History_ModalError {
            get {
                return ResourceManager.GetString("History_ModalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading analysis....
        /// </summary>
        public static string History_ModalLoading {
            get {
                return ResourceManager.GetString("History_ModalLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Analysis.
        /// </summary>
        public static string History_ModalTitle {
            get {
                return ResourceManager.GetString("History_ModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No vulnerabilities found.
        /// </summary>
        public static string History_NoVulnerabilities {
            get {
                return ResourceManager.GetString("History_NoVulnerabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by URL....
        /// </summary>
        public static string History_SearchPlaceholder {
            get {
                return ResourceManager.GetString("History_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date (Oldest).
        /// </summary>
        public static string History_SortDateAsc {
            get {
                return ResourceManager.GetString("History_SortDateAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by: Recent.
        /// </summary>
        public static string History_SortRecent {
            get {
                return ResourceManager.GetString("History_SortRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerabilities (Low to High).
        /// </summary>
        public static string History_SortVulnAsc {
            get {
                return ResourceManager.GetString("History_SortVulnAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerabilities (High to Low).
        /// </summary>
        public static string History_SortVulnDesc {
            get {
                return ResourceManager.GetString("History_SortVulnDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review and analyze past scans to keep your websites secure with ScanGuard’s AI-powered insights..
        /// </summary>
        public static string History_Subtitle {
            get {
                return ResourceManager.GetString("History_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan History.
        /// </summary>
        public static string History_Title {
            get {
                return ResourceManager.GetString("History_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scanned websites yet. Be the first!.
        /// </summary>
        public static string Home_Empty_Message {
            get {
                return ResourceManager.GetString("Home_Empty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced cybersecurity solutions with ScanGuard. Protect your websites, files, and data in real-time..
        /// </summary>
        public static string Home_Hero_Subtitle {
            get {
                return ResourceManager.GetString("Home_Hero_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building a Safer Digital World.
        /// </summary>
        public static string Home_Section_Title {
            get {
                return ResourceManager.GetString("Home_Section_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal for businesses and professionals needing advanced security features and priority support..
        /// </summary>
        public static string IdealForBusinesses {
            get {
                return ResourceManager.GetString("IdealForBusinesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innovation.
        /// </summary>
        public static string Innovation {
            get {
                return ResourceManager.GetString("Innovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolving to outpace cyber threats..
        /// </summary>
        public static string InnovationText {
            get {
                return ResourceManager.GetString("InnovationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant notifications for potential threats..
        /// </summary>
        public static string InstantNotifications {
            get {
                return ResourceManager.GetString("InstantNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Our Mission.
        /// </summary>
        public static string JoinOurMission {
            get {
                return ResourceManager.GetString("JoinOurMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join ScanGuard today and take control of your cybersecurity..
        /// </summary>
        public static string JoinScanGuard {
            get {
                return ResourceManager.GetString("JoinScanGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regularly scan your files to ensure they are free from threats. Try our website scanner for comprehensive security..
        /// </summary>
        public static string Keep_Your_Files_SecureText {
            get {
                return ResourceManager.GetString("Keep Your Files SecureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Your Files Secure.
        /// </summary>
        public static string KeepYourFilesSecure {
            get {
                return ResourceManager.GetString("KeepYourFilesSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հայերեն.
        /// </summary>
        public static string Language_Armenian {
            get {
                return ResourceManager.GetString("Language_Armenian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Security Updates.
        /// </summary>
        public static string LatestSecurityUpdates {
            get {
                return ResourceManager.GetString("LatestSecurityUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_ButtonSubmit {
            get {
                return ResourceManager.GetString("Login_ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Login_FormTitle {
            get {
                return ResourceManager.GetString("Login_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string Login_LabelRememberMe {
            get {
                return ResourceManager.GetString("Login_LabelRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Login_LinkSignUp {
            get {
                return ResourceManager.GetString("Login_LinkSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Login_PlaceholderEmail {
            get {
                return ResourceManager.GetString("Login_PlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_PlaceholderPassword {
            get {
                return ResourceManager.GetString("Login_PlaceholderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t have an account?.
        /// </summary>
        public static string Login_TextNoAccount {
            get {
                return ResourceManager.GetString("Login_TextNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Login2fa_ButtonSubmit {
            get {
                return ResourceManager.GetString("Login2fa_ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login is protected with an authenticator app. Enter your authenticator code below..
        /// </summary>
        public static string Login2fa_Description {
            get {
                return ResourceManager.GetString("Login2fa_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have access to your authenticator device? You can log in with a recovery code..
        /// </summary>
        public static string Login2fa_FooterText {
            get {
                return ResourceManager.GetString("Login2fa_FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this machine.
        /// </summary>
        public static string Login2fa_LabelRememberMachine {
            get {
                return ResourceManager.GetString("Login2fa_LabelRememberMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in with a recovery code.
        /// </summary>
        public static string Login2fa_LinkRecoveryCode {
            get {
                return ResourceManager.GetString("Login2fa_LinkRecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator Code.
        /// </summary>
        public static string Login2fa_PlaceholderCode {
            get {
                return ResourceManager.GetString("Login2fa_PlaceholderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor Authentication.
        /// </summary>
        public static string Login2fa_Title {
            get {
                return ResourceManager.GetString("Login2fa_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid 2FA code.
        /// </summary>
        public static string Login2fa_ValidateCode {
            get {
                return ResourceManager.GetString("Login2fa_ValidateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malicious.
        /// </summary>
        public static string Malicious {
            get {
                return ResourceManager.GetString("Malicious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly security consultation with experts.
        /// </summary>
        public static string MonthlySecurity {
            get {
                return ResourceManager.GetString("MonthlySecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string Nav_AboutUs {
            get {
                return ResourceManager.GetString("Nav_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All News.
        /// </summary>
        public static string Nav_AllNews {
            get {
                return ResourceManager.GetString("Nav_AllNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Nav_Chat {
            get {
                return ResourceManager.GetString("Nav_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporation.
        /// </summary>
        public static string Nav_Corporation {
            get {
                return ResourceManager.GetString("Nav_Corporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Nav_Files {
            get {
                return ResourceManager.GetString("Nav_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Scanner.
        /// </summary>
        public static string Nav_FileScanner {
            get {
                return ResourceManager.GetString("Nav_FileScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Corp Requests.
        /// </summary>
        public static string Nav_GetCorpRequests {
            get {
                return ResourceManager.GetString("Nav_GetCorpRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Token.
        /// </summary>
        public static string Nav_GetToken {
            get {
                return ResourceManager.GetString("Nav_GetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Nav_History {
            get {
                return ResourceManager.GetString("Nav_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Nav_Login {
            get {
                return ResourceManager.GetString("Nav_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Nav_Logout {
            get {
                return ResourceManager.GetString("Nav_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Nav_Main {
            get {
                return ResourceManager.GetString("Nav_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string Nav_News {
            get {
                return ResourceManager.GetString("Nav_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Nav_Notifications {
            get {
                return ResourceManager.GetString("Nav_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        public static string Nav_Premium {
            get {
                return ResourceManager.GetString("Nav_Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Nav_Profile {
            get {
                return ResourceManager.GetString("Nav_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Nav_Register {
            get {
                return ResourceManager.GetString("Nav_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Nav_Review {
            get {
                return ResourceManager.GetString("Nav_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan File.
        /// </summary>
        public static string Nav_ScanFile {
            get {
                return ResourceManager.GetString("Nav_ScanFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned Files.
        /// </summary>
        public static string Nav_ScannedFiles {
            get {
                return ResourceManager.GetString("Nav_ScannedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned Sites.
        /// </summary>
        public static string Nav_ScannedSites {
            get {
                return ResourceManager.GetString("Nav_ScannedSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner.
        /// </summary>
        public static string Nav_Scanner {
            get {
                return ResourceManager.GetString("Nav_Scanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites.
        /// </summary>
        public static string Nav_Sites {
            get {
                return ResourceManager.GetString("Nav_Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Nav_Users {
            get {
                return ResourceManager.GetString("Nav_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Impact.
        /// </summary>
        public static string OurImpact {
            get {
                return ResourceManager.GetString("OurImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Purpose.
        /// </summary>
        public static string OurPurpose {
            get {
                return ResourceManager.GetString("OurPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string OurTeam {
            get {
                return ResourceManager.GetString("OurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect for individuals and small projects looking to secure their digital assets with essential tools..
        /// </summary>
        public static string PerfectFor {
            get {
                return ResourceManager.GetString("PerfectFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision.
        /// </summary>
        public static string Precision {
            get {
                return ResourceManager.GetString("Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accurate detection of every vulnerability..
        /// </summary>
        public static string PrecisionText {
            get {
                return ResourceManager.GetString("PrecisionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium community chat with other users.
        /// </summary>
        public static string PremiumCommunityChat {
            get {
                return ResourceManager.GetString("PremiumCommunityChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority support with 24/7 assistance.
        /// </summary>
        public static string PrioritySupport {
            get {
                return ResourceManager.GetString("PrioritySupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Profile_ButtonSave {
            get {
                return ResourceManager.GetString("Profile_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Profile_LabelEmail {
            get {
                return ResourceManager.GetString("Profile_LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Profile_LabelFullName {
            get {
                return ResourceManager.GetString("Profile_LabelFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Profile_LabelPhoneNumber {
            get {
                return ResourceManager.GetString("Profile_LabelPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your full name.
        /// </summary>
        public static string Profile_PlaceholderFullName {
            get {
                return ResourceManager.GetString("Profile_PlaceholderFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number.
        /// </summary>
        public static string Profile_PlaceholderPhoneNumber {
            get {
                return ResourceManager.GetString("Profile_PlaceholderPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Profile_StatusAdmin {
            get {
                return ResourceManager.GetString("Profile_StatusAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        public static string Profile_StatusPremium {
            get {
                return ResourceManager.GetString("Profile_StatusPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection.
        /// </summary>
        public static string Protection {
            get {
                return ResourceManager.GetString("Protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robust scanning to keep your assets secure..
        /// </summary>
        public static string ProtectionText {
            get {
                return ResourceManager.GetString("ProtectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide user-friendly scanning solutions..
        /// </summary>
        public static string PurposeDotOne {
            get {
                return ResourceManager.GetString("PurposeDotOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure affordability without compromise..
        /// </summary>
        public static string PurposeDotThree {
            get {
                return ResourceManager.GetString("PurposeDotThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay ahead of evolving cyber threats..
        /// </summary>
        public static string PurposeDotTwo {
            get {
                return ResourceManager.GetString("PurposeDotTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founded in 2025, ScanGuard exists to simplify cybersecurity. Our purpose is to empower businesses, developers, and individuals with accessible tools to protect their websites and files from vulnerabilities..
        /// </summary>
        public static string PurposeTextOne {
            get {
                return ResourceManager.GetString("PurposeTextOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re driven by a commitment to deliver fast, accurate scans that catch threats before they strike. Our goal is a digital world where safety is seamless and universal..
        /// </summary>
        public static string PurposeTextTwo {
            get {
                return ResourceManager.GetString("PurposeTextTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Scan More?.
        /// </summary>
        public static string ReadyToScan {
            get {
                return ResourceManager.GetString("ReadyToScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Secure Your Online Presence?.
        /// </summary>
        public static string ReadyToSecure {
            get {
                return ResourceManager.GetString("ReadyToSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-time vulnerability detection for websites and files..
        /// </summary>
        public static string RealTime {
            get {
                return ResourceManager.GetString("RealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-Time Alerts.
        /// </summary>
        public static string RealTimeAlerts {
            get {
                return ResourceManager.GetString("RealTimeAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_ButtonSubmit {
            get {
                return ResourceManager.GetString("Register_ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string Register_FormTitle {
            get {
                return ResourceManager.GetString("Register_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Register_LinkLogin {
            get {
                return ResourceManager.GetString("Register_LinkLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Register_PageTitle {
            get {
                return ResourceManager.GetString("Register_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Register_PlaceholderEmail {
            get {
                return ResourceManager.GetString("Register_PlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string Register_PlaceholderFullName {
            get {
                return ResourceManager.GetString("Register_PlaceholderFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Register_PlaceholderPassword {
            get {
                return ResourceManager.GetString("Register_PlaceholderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string Register_TextHaveAccount {
            get {
                return ResourceManager.GetString("Register_TextHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve sent a confirmation email to {0}. Please check your inbox and click the confirmation link to activate your ScanGuard account..
        /// </summary>
        public static string RegisterConfirm_Description {
            get {
                return ResourceManager.GetString("RegisterConfirm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Your Email.
        /// </summary>
        public static string RegisterConfirm_FormTitle {
            get {
                return ResourceManager.GetString("RegisterConfirm_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your first line of defense in the digital world.
        /// </summary>
        public static string RegisterConfirm_Slogan {
            get {
                return ResourceManager.GetString("RegisterConfirm_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open your email inbox.
        /// </summary>
        public static string RegisterConfirm_Step1 {
            get {
                return ResourceManager.GetString("RegisterConfirm_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find our email (check spam folder too).
        /// </summary>
        public static string RegisterConfirm_Step2 {
            get {
                return ResourceManager.GetString("RegisterConfirm_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the confirmation link.
        /// </summary>
        public static string RegisterConfirm_Step3 {
            get {
                return ResourceManager.GetString("RegisterConfirm_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register confirmation.
        /// </summary>
        public static string RegisterConfirm_Title {
            get {
                return ResourceManager.GetString("RegisterConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Count.
        /// </summary>
        public static string ScanCount {
            get {
                return ResourceManager.GetString("ScanCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Date.
        /// </summary>
        public static string ScanDate {
            get {
                return ResourceManager.GetString("ScanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned.
        /// </summary>
        public static string Scanned {
            get {
                return ResourceManager.GetString("Scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Scan.
        /// </summary>
        public static string Scanner_ButtonStart {
            get {
                return ResourceManager.GetString("Scanner_ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Another URL.
        /// </summary>
        public static string Scanner_CtaButton {
            get {
                return ResourceManager.GetString("Scanner_CtaButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run regular scans to keep your website safe from vulnerabilities..
        /// </summary>
        public static string Scanner_CtaSubtitle {
            get {
                return ResourceManager.GetString("Scanner_CtaSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay Secure with ScanGuard.
        /// </summary>
        public static string Scanner_CtaTitle {
            get {
                return ResourceManager.GetString("Scanner_CtaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Your Website.
        /// </summary>
        public static string Scanner_FormTitle {
            get {
                return ResourceManager.GetString("Scanner_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak authentication lets attackers bypass login or hijack sessions, gaining unauthorized access..
        /// </summary>
        public static string Scanner_InfoBrokenAuthDescription {
            get {
                return ResourceManager.GetString("Scanner_InfoBrokenAuthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tricks authenticated users into performing unintended actions (e.g., changing settings) via forged requests..
        /// </summary>
        public static string Scanner_InfoCSRFDescription {
            get {
                return ResourceManager.GetString("Scanner_InfoCSRFDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misconfigured servers expose directory contents, revealing sensitive files or structure..
        /// </summary>
        public static string Scanner_InfoDirectoryListingDescription {
            get {
                return ResourceManager.GetString("Scanner_InfoDirectoryListingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploits header manipulation to inject content or redirect users to malicious sites..
        /// </summary>
        public static string Scanner_InfoHTTPResponseSplittingDescription {
            get {
                return ResourceManager.GetString("Scanner_InfoHTTPResponseSplittingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insecure Direct Object References allow attackers to access unauthorized resources by manipulating identifiers..
        /// </summary>
        public static string Scanner_InfoIDORDescription {
            get {
                return ResourceManager.GetString("Scanner_InfoIDORDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows attackers to include local files (e.g., config files), potentially exposing sensitive data..
        /// </summary>
        public static string Scanner_InfoLFIDescription {
            get {
                return ResourceManager.GetString("Scanner_InfoLFIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-HTTPS connections expose data to interception or tampering by attackers..
        /// </summary>
        public static string Scanner_InfoNotSecureDomainDescription {
            get {
                return ResourceManager.GetString("Scanner_InfoNotSecureDomainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deceptive techniques trick users into revealing credentials via fake pages or links..
        /// </summary>
        public static string Scanner_InfoPhishingDescription {
            get {
                return ResourceManager.GetString("Scanner_InfoPhishingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permits inclusion of remote malicious files, often leading to code execution on the server..
        /// </summary>
        public static string Scanner_InfoRFIDescription {
            get {
                return ResourceManager.GetString("Scanner_InfoRFIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improper settings (e.g., open ports, default credentials) expose vulnerabilities in servers or apps..
        /// </summary>
        public static string Scanner_InfoSecurityMisconfigDescription {
            get {
                return ResourceManager.GetString("Scanner_InfoSecurityMisconfigDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows attackers to inject malicious SQL code into input fields, potentially accessing or altering database content..
        /// </summary>
        public static string Scanner_InfoSQLiDescription {
            get {
                return ResourceManager.GetString("Scanner_InfoSQLiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerability Information.
        /// </summary>
        public static string Scanner_InfoTitle {
            get {
                return ResourceManager.GetString("Scanner_InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untrusted redirect inputs can send users to malicious sites, aiding phishing attacks..
        /// </summary>
        public static string Scanner_InfoUnvalidatedRedirectDescription {
            get {
                return ResourceManager.GetString("Scanner_InfoUnvalidatedRedirectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple passwords make accounts vulnerable to brute-force or guessing attacks..
        /// </summary>
        public static string Scanner_InfoWeakPasswordDescription {
            get {
                return ResourceManager.GetString("Scanner_InfoWeakPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables attackers to inject scripts into web pages, which run in users’ browsers, potentially stealing data or defacing the site..
        /// </summary>
        public static string Scanner_InfoXSSDescription {
            get {
                return ResourceManager.GetString("Scanner_InfoXSSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect your website by identifying security risks with ScanGuard’s advanced scanning technology..
        /// </summary>
        public static string Scanner_IntroSubtitle {
            get {
                return ResourceManager.GetString("Scanner_IntroSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URL to Scan.
        /// </summary>
        public static string Scanner_LabelUrl {
            get {
                return ResourceManager.GetString("Scanner_LabelUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://example.com.
        /// </summary>
        public static string Scanner_PlaceholderUrl {
            get {
                return ResourceManager.GetString("Scanner_PlaceholderUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Scanner_PortClosed {
            get {
                return ResourceManager.GetString("Scanner_PortClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Scanner_PortOpen {
            get {
                return ResourceManager.GetString("Scanner_PortOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Scan Results.
        /// </summary>
        public static string Scanner_PortResultsTitle {
            get {
                return ResourceManager.GetString("Scanner_PortResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected.
        /// </summary>
        public static string Scanner_ResultDetected {
            get {
                return ResourceManager.GetString("Scanner_ResultDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insecure.
        /// </summary>
        public static string Scanner_ResultInsecure {
            get {
                return ResourceManager.GetString("Scanner_ResultInsecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Detected.
        /// </summary>
        public static string Scanner_ResultNotDetected {
            get {
                return ResourceManager.GetString("Scanner_ResultNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure.
        /// </summary>
        public static string Scanner_ResultSecure {
            get {
                return ResourceManager.GetString("Scanner_ResultSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Results.
        /// </summary>
        public static string Scanner_ResultsTitle {
            get {
                return ResourceManager.GetString("Scanner_ResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerability Scanner.
        /// </summary>
        public static string Scanner_Title {
            get {
                return ResourceManager.GetString("Scanner_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner Text.
        /// </summary>
        public static string ScannerText {
            get {
                return ResourceManager.GetString("ScannerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scans Performed.
        /// </summary>
        public static string ScansPerformed {
            get {
                return ResourceManager.GetString("ScansPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Website.
        /// </summary>
        public static string ScanWebButton {
            get {
                return ResourceManager.GetString("ScanWebButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Your Website.
        /// </summary>
        public static string ScanYourWebsite {
            get {
                return ResourceManager.GetString("ScanYourWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Your Future.
        /// </summary>
        public static string SecureYourFuture {
            get {
                return ResourceManager.GetString("SecureYourFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security news updates and insights.
        /// </summary>
        public static string SecurityNews {
            get {
                return ResourceManager.GetString("SecurityNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Sidebar_ChangePassword {
            get {
                return ResourceManager.GetString("Sidebar_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Logins.
        /// </summary>
        public static string Sidebar_ExternalLogins {
            get {
                return ResourceManager.GetString("Sidebar_ExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Sidebar_Profile {
            get {
                return ResourceManager.GetString("Sidebar_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Factor Auth.
        /// </summary>
        public static string Sidebar_TwoFactorAuth {
            get {
                return ResourceManager.GetString("Sidebar_TwoFactorAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up Now.
        /// </summary>
        public static string SignUpNow {
            get {
                return ResourceManager.GetString("SignUpNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Scanning.
        /// </summary>
        public static string StartScanning {
            get {
                return ResourceManager.GetString("StartScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ScanGuard.
        /// </summary>
        public static string String1About_ScanGuard {
            get {
                return ResourceManager.GetString("String1About ScanGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailored Plans for Your Needs.
        /// </summary>
        public static string TailoredPlans {
            get {
                return ResourceManager.GetString("TailoredPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harutyun Mkrtchyan.
        /// </summary>
        public static string TeamOneName {
            get {
                return ResourceManager.GetString("TeamOneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder &amp; CEO.
        /// </summary>
        public static string TeamOneState {
            get {
                return ResourceManager.GetString("TeamOneState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harutyun and Davit launched ScanGuard in 2025 with a vision to make cybersecurity simple. Her expertise in software engineering drives our mission to protect the digital world..
        /// </summary>
        public static string TeamOneText {
            get {
                return ResourceManager.GetString("TeamOneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Davit Gasparyan.
        /// </summary>
        public static string TeamTwoName {
            get {
                return ResourceManager.GetString("TeamTwoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Developer.
        /// </summary>
        public static string TeamTwoState {
            get {
                return ResourceManager.GetString("TeamTwoState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Davit and Harutyun build the heart of our scanning tools. With a passion for AI and security, he ensures our platform is powerful and intuitive..
        /// </summary>
        public static string TeamTwoText {
            get {
                return ResourceManager.GetString("TeamTwoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram bot access with full website features.
        /// </summary>
        public static string TelegramBot {
            get {
                return ResourceManager.GetString("TelegramBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 2FA.
        /// </summary>
        public static string Tfa_ButtonDisable2fa {
            get {
                return ResourceManager.GetString("Tfa_ButtonDisable2fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget this browser.
        /// </summary>
        public static string Tfa_ButtonForgetBrowser {
            get {
                return ResourceManager.GetString("Tfa_ButtonForgetBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset recovery codes.
        /// </summary>
        public static string Tfa_ButtonResetCodes {
            get {
                return ResourceManager.GetString("Tfa_ButtonResetCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your two-factor authentication settings..
        /// </summary>
        public static string Tfa_Description {
            get {
                return ResourceManager.GetString("Tfa_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} recovery codes left..
        /// </summary>
        public static string Tfa_FewRecoveryCodes {
            get {
                return ResourceManager.GetString("Tfa_FewRecoveryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should generate a new set of recovery codes..
        /// </summary>
        public static string Tfa_FewRecoveryCodesAction {
            get {
                return ResourceManager.GetString("Tfa_FewRecoveryCodesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add authenticator app.
        /// </summary>
        public static string Tfa_LinkAddAuthenticator {
            get {
                return ResourceManager.GetString("Tfa_LinkAddAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator app.
        /// </summary>
        public static string Tfa_LinkResetAuthenticator {
            get {
                return ResourceManager.GetString("Tfa_LinkResetAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up authenticator app.
        /// </summary>
        public static string Tfa_LinkSetupAuthenticator {
            get {
                return ResourceManager.GetString("Tfa_LinkSetupAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no recovery codes left..
        /// </summary>
        public static string Tfa_NoRecoveryCodes {
            get {
                return ResourceManager.GetString("Tfa_NoRecoveryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must generate a new set of recovery codes before you can log in with a recovery code..
        /// </summary>
        public static string Tfa_NoRecoveryCodesAction {
            get {
                return ResourceManager.GetString("Tfa_NoRecoveryCodesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have 1 recovery code left..
        /// </summary>
        public static string Tfa_OneRecoveryCode {
            get {
                return ResourceManager.GetString("Tfa_OneRecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can generate a new set of recovery codes..
        /// </summary>
        public static string Tfa_OneRecoveryCodeAction {
            get {
                return ResourceManager.GetString("Tfa_OneRecoveryCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy and cookie policy have not been accepted..
        /// </summary>
        public static string Tfa_PrivacyNotAccepted {
            get {
                return ResourceManager.GetString("Tfa_PrivacyNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the policy before you can enable two-factor authentication..
        /// </summary>
        public static string Tfa_PrivacyNotAcceptedAction {
            get {
                return ResourceManager.GetString("Tfa_PrivacyNotAcceptedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator App.
        /// </summary>
        public static string Tfa_SubtitleAuthenticator {
            get {
                return ResourceManager.GetString("Tfa_SubtitleAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Factor Authentication.
        /// </summary>
        public static string Tfa_Title {
            get {
                return ResourceManager.GetString("Tfa_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Security Hotspots.
        /// </summary>
        public static string TopSecurityHotspots {
            get {
                return ResourceManager.GetString("TopSecurityHotspots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted by Our Community.
        /// </summary>
        public static string Trusted {
            get {
                return ResourceManager.GetString("Trusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Authenticator App.
        /// </summary>
        public static string TwoFactor_ConfigureAppTitle {
            get {
                return ResourceManager.GetString("TwoFactor_ConfigureAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how to enable QR code generation..
        /// </summary>
        public static string TwoFactor_QRCodeHelpLink {
            get {
                return ResourceManager.GetString("TwoFactor_QRCodeHelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up two-factor authentication with an authenticator app..
        /// </summary>
        public static string TwoFactor_SetupDescription {
            get {
                return ResourceManager.GetString("TwoFactor_SetupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install a two-factor authenticator app like Microsoft Authenticator or Google Authenticator..
        /// </summary>
        public static string TwoFactor_Step1Description {
            get {
                return ResourceManager.GetString("TwoFactor_Step1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Download an App.
        /// </summary>
        public static string TwoFactor_Step1Title {
            get {
                return ResourceManager.GetString("TwoFactor_Step1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the QR code below or enter the key into your authenticator app. Spaces and casing do not matter..
        /// </summary>
        public static string TwoFactor_Step2Description {
            get {
                return ResourceManager.GetString("TwoFactor_Step2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Scan QR Code.
        /// </summary>
        public static string TwoFactor_Step2Title {
            get {
                return ResourceManager.GetString("TwoFactor_Step2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the unique code provided by your authenticator app to complete setup..
        /// </summary>
        public static string TwoFactor_Step3Description {
            get {
                return ResourceManager.GetString("TwoFactor_Step3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Verify Code.
        /// </summary>
        public static string TwoFactor_Step3Title {
            get {
                return ResourceManager.GetString("TwoFactor_Step3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string TwoFactor_VerificationCodeLabel {
            get {
                return ResourceManager.GetString("TwoFactor_VerificationCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter code.
        /// </summary>
        public static string TwoFactor_VerificationCodePlaceholder {
            get {
                return ResourceManager.GetString("TwoFactor_VerificationCodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string TwoFactor_VerifyButton {
            get {
                return ResourceManager.GetString("TwoFactor_VerifyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited scans for websites and files.
        /// </summary>
        public static string UnlimitedScans {
            get {
                return ResourceManager.GetString("UnlimitedScans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to Premium.
        /// </summary>
        public static string UpgradeToPremium {
            get {
                return ResourceManager.GetString("UpgradeToPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 3 file scans per day.
        /// </summary>
        public static string UpTo3File {
            get {
                return ResourceManager.GetString("UpTo3File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Trust.
        /// </summary>
        public static string UserTrust {
            get {
                return ResourceManager.GetString("UserTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified User.
        /// </summary>
        public static string VerifiedUser {
            get {
                return ResourceManager.GetString("VerifiedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View More.
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerabilities Detected.
        /// </summary>
        public static string VulnerabilitiesDetected {
            get {
                return ResourceManager.GetString("VulnerabilitiesDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vulnerabilities found.
        /// </summary>
        public static string VulnerabilitiesFound {
            get {
                return ResourceManager.GetString("VulnerabilitiesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerability Scanner.
        /// </summary>
        public static string VulnerabilityScanner {
            get {
                return ResourceManager.GetString("VulnerabilityScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerability Type.
        /// </summary>
        public static string VulnerabilityType {
            get {
                return ResourceManager.GetString("VulnerabilityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Scans.
        /// </summary>
        public static string WebsiteScans {
            get {
                return ResourceManager.GetString("WebsiteScans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Websites Scanned.
        /// </summary>
        public static string WebsitesScanned {
            get {
                return ResourceManager.GetString("WebsitesScanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website URL.
        /// </summary>
        public static string WebsiteURL {
            get {
                return ResourceManager.GetString("WebsiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Drives Us.
        /// </summary>
        public static string WhatDrivesUs {
            get {
                return ResourceManager.GetString("WhatDrivesUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Choose ScanGuard.
        /// </summary>
        public static string WhyChooseScanGuard {
            get {
                return ResourceManager.GetString("WhyChooseScanGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        public static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a Review.
        /// </summary>
        public static string WriteaReview {
            get {
                return ResourceManager.GetString("WriteaReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your.
        /// </summary>
        public static string Your {
            get {
                return ResourceManager.GetString("Your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your  Email.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message.
        /// </summary>
        public static string YourMessage {
            get {
                return ResourceManager.GetString("YourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Security Advantage.
        /// </summary>
        public static string YourSecurityAdvantage {
            get {
                return ResourceManager.GetString("YourSecurityAdvantage", resourceCulture);
            }
        }
    }
}
