//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanGuard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScanGuard.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re dedicated to making the digital world safer with powerful tools to scan and secure websites and files from vulnerabilities..
        /// </summary>
        public static string About_text {
            get {
                return ResourceManager.GetString("About_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ScanGuard.
        /// </summary>
        public static string AboutScanGuard {
            get {
                return ResourceManager.GetString("AboutScanGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        public static string Accessibility {
            get {
                return ResourceManager.GetString("Accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cybersecurity for everyone, everywhere..
        /// </summary>
        public static string AccessibilityText {
            get {
                return ResourceManager.GetString("AccessibilityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to community forums.
        /// </summary>
        public static string AccessToCommunity {
            get {
                return ResourceManager.GetString("AccessToCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced analytics and detailed reports.
        /// </summary>
        public static string AdvancedAnalytics {
            get {
                return ResourceManager.GetString("AdvancedAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Scanning.
        /// </summary>
        public static string AdvancedScanning {
            get {
                return ResourceManager.GetString("AdvancedScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All-in-one solution for your digital security..
        /// </summary>
        public static string AllInOne {
            get {
                return ResourceManager.GetString("AllInOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzed.
        /// </summary>
        public static string Analyzed {
            get {
                return ResourceManager.GetString("Analyzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API access for integration with your tools.
        /// </summary>
        public static string APIAccess {
            get {
                return ResourceManager.GetString("APIAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic support via email (response within 48 hours).
        /// </summary>
        public static string BasicSupport {
            get {
                return ResourceManager.GetString("BasicSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI-Powered.
        /// </summary>
        public static string ChooseAI {
            get {
                return ResourceManager.GetString("ChooseAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart tech for smarter detection..
        /// </summary>
        public static string ChooseAIText {
            get {
                return ResourceManager.GetString("ChooseAIText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost-Effective.
        /// </summary>
        public static string ChooseCost {
            get {
                return ResourceManager.GetString("ChooseCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium security at fair prices..
        /// </summary>
        public static string ChooseCostText {
            get {
                return ResourceManager.GetString("ChooseCostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Scans.
        /// </summary>
        public static string ChooseFast {
            get {
                return ResourceManager.GetString("ChooseFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get results in seconds, not hours..
        /// </summary>
        public static string ChooseFastText {
            get {
                return ResourceManager.GetString("ChooseFastText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string ChooseSupport {
            get {
                return ResourceManager.GetString("ChooseSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help whenever you need it..
        /// </summary>
        public static string ChooseSupportText {
            get {
                return ResourceManager.GetString("ChooseSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients Protected.
        /// </summary>
        public static string ClientsProtected {
            get {
                return ResourceManager.GetString("ClientsProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehensive Protection.
        /// </summary>
        public static string ComprehensiveProtection {
            get {
                return ResourceManager.GetString("ComprehensiveProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us for updates and tips on staying secure online..
        /// </summary>
        public static string ConnectText {
            get {
                return ResourceManager.GetString("ConnectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with ScanGuard.
        /// </summary>
        public static string ConnectwithScanGuard {
            get {
                return ResourceManager.GetString("ConnectwithScanGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom scan schedules and automation.
        /// </summary>
        public static string CustomScan {
            get {
                return ResourceManager.GetString("CustomScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected threat on.
        /// </summary>
        public static string DetectedThreatOn {
            get {
                return ResourceManager.GetString("DetectedThreatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital.
        /// </summary>
        public static string Digital {
            get {
                return ResourceManager.GetString("Digital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email։.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URL to Scan.
        /// </summary>
        public static string EnterURLtoScan {
            get {
                return ResourceManager.GetString("EnterURLtoScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essential scanning for websites and files.
        /// </summary>
        public static string Essential {
            get {
                return ResourceManager.GetString("Essential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore advanced tools to secure your digital world..
        /// </summary>
        public static string ExploreAdvanced {
            get {
                return ResourceManager.GetString("ExploreAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files Analyzed.
        /// </summary>
        public static string FilesAnalyzed {
            get {
                return ResourceManager.GetString("FilesAnalyzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start scanning now.
        /// </summary>
        public static string FutureStartScanningNow {
            get {
                return ResourceManager.GetString("FutureStartScanningNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join ScanGuard to protect your websites and files with confidence..
        /// </summary>
        public static string FutureText {
            get {
                return ResourceManager.GetString("FutureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in Touch.
        /// </summary>
        public static string GetinTouch {
            get {
                return ResourceManager.GetString("GetinTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Dashboard.
        /// </summary>
        public static string GoToDashboard {
            get {
                return ResourceManager.GetString("GoToDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guard.
        /// </summary>
        public static string Guard {
            get {
                return ResourceManager.GetString("Guard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy Users.
        /// </summary>
        public static string HappyUsers {
            get {
                return ResourceManager.GetString("HappyUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scanned websites yet. Be the first!.
        /// </summary>
        public static string Home_Empty_Message {
            get {
                return ResourceManager.GetString("Home_Empty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced cybersecurity solutions with ScanGuard. Protect your websites, files, and data in real-time..
        /// </summary>
        public static string Home_Hero_Subtitle {
            get {
                return ResourceManager.GetString("Home_Hero_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building a Safer Digital World.
        /// </summary>
        public static string Home_Section_Title {
            get {
                return ResourceManager.GetString("Home_Section_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal for businesses and professionals needing advanced security features and priority support..
        /// </summary>
        public static string IdealForBusinesses {
            get {
                return ResourceManager.GetString("IdealForBusinesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innovation.
        /// </summary>
        public static string Innovation {
            get {
                return ResourceManager.GetString("Innovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolving to outpace cyber threats..
        /// </summary>
        public static string InnovationText {
            get {
                return ResourceManager.GetString("InnovationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant notifications for potential threats..
        /// </summary>
        public static string InstantNotifications {
            get {
                return ResourceManager.GetString("InstantNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Our Mission.
        /// </summary>
        public static string JoinOurMission {
            get {
                return ResourceManager.GetString("JoinOurMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join ScanGuard today and take control of your cybersecurity..
        /// </summary>
        public static string JoinScanGuard {
            get {
                return ResourceManager.GetString("JoinScanGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Security Updates.
        /// </summary>
        public static string LatestSecurityUpdates {
            get {
                return ResourceManager.GetString("LatestSecurityUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly security consultation with experts.
        /// </summary>
        public static string MonthlySecurity {
            get {
                return ResourceManager.GetString("MonthlySecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Impact.
        /// </summary>
        public static string OurImpact {
            get {
                return ResourceManager.GetString("OurImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Purpose.
        /// </summary>
        public static string OurPurpose {
            get {
                return ResourceManager.GetString("OurPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string OurTeam {
            get {
                return ResourceManager.GetString("OurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect for individuals and small projects looking to secure their digital assets with essential tools..
        /// </summary>
        public static string PerfectFor {
            get {
                return ResourceManager.GetString("PerfectFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision.
        /// </summary>
        public static string Precision {
            get {
                return ResourceManager.GetString("Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accurate detection of every vulnerability..
        /// </summary>
        public static string PrecisionText {
            get {
                return ResourceManager.GetString("PrecisionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium community chat with other users.
        /// </summary>
        public static string PremiumCommunityChat {
            get {
                return ResourceManager.GetString("PremiumCommunityChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority support with 24/7 assistance.
        /// </summary>
        public static string PrioritySupport {
            get {
                return ResourceManager.GetString("PrioritySupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection.
        /// </summary>
        public static string Protection {
            get {
                return ResourceManager.GetString("Protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robust scanning to keep your assets secure..
        /// </summary>
        public static string ProtectionText {
            get {
                return ResourceManager.GetString("ProtectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide user-friendly scanning solutions..
        /// </summary>
        public static string PurposeDotOne {
            get {
                return ResourceManager.GetString("PurposeDotOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure affordability without compromise..
        /// </summary>
        public static string PurposeDotThree {
            get {
                return ResourceManager.GetString("PurposeDotThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay ahead of evolving cyber threats..
        /// </summary>
        public static string PurposeDotTwo {
            get {
                return ResourceManager.GetString("PurposeDotTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founded in 2025, ScanGuard exists to simplify cybersecurity. Our purpose is to empower businesses, developers, and individuals with accessible tools to protect their websites and files from vulnerabilities..
        /// </summary>
        public static string PurposeTextOne {
            get {
                return ResourceManager.GetString("PurposeTextOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re driven by a commitment to deliver fast, accurate scans that catch threats before they strike. Our goal is a digital world where safety is seamless and universal..
        /// </summary>
        public static string PurposeTextTwo {
            get {
                return ResourceManager.GetString("PurposeTextTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Scan More?.
        /// </summary>
        public static string ReadyToScan {
            get {
                return ResourceManager.GetString("ReadyToScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Secure Your Online Presence?.
        /// </summary>
        public static string ReadyToSecure {
            get {
                return ResourceManager.GetString("ReadyToSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-time vulnerability detection for websites and files..
        /// </summary>
        public static string RealTime {
            get {
                return ResourceManager.GetString("RealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-Time Alerts.
        /// </summary>
        public static string RealTimeAlerts {
            get {
                return ResourceManager.GetString("RealTimeAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Count.
        /// </summary>
        public static string ScanCount {
            get {
                return ResourceManager.GetString("ScanCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned.
        /// </summary>
        public static string Scanned {
            get {
                return ResourceManager.GetString("Scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner Text.
        /// </summary>
        public static string ScannerText {
            get {
                return ResourceManager.GetString("ScannerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scans Performed.
        /// </summary>
        public static string ScansPerformed {
            get {
                return ResourceManager.GetString("ScansPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Your Website.
        /// </summary>
        public static string ScanYourWebsite {
            get {
                return ResourceManager.GetString("ScanYourWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Your Future.
        /// </summary>
        public static string SecureYourFuture {
            get {
                return ResourceManager.GetString("SecureYourFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security news updates and insights.
        /// </summary>
        public static string SecurityNews {
            get {
                return ResourceManager.GetString("SecurityNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up Now.
        /// </summary>
        public static string SignUpNow {
            get {
                return ResourceManager.GetString("SignUpNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Scanning.
        /// </summary>
        public static string StartScanning {
            get {
                return ResourceManager.GetString("StartScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailored Plans for Your Needs.
        /// </summary>
        public static string TailoredPlans {
            get {
                return ResourceManager.GetString("TailoredPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harutyun Mkrtchyan.
        /// </summary>
        public static string TeamOneName {
            get {
                return ResourceManager.GetString("TeamOneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder &amp; CEO.
        /// </summary>
        public static string TeamOneState {
            get {
                return ResourceManager.GetString("TeamOneState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harutyun and Davit launched ScanGuard in 2025 with a vision to make cybersecurity simple. Her expertise in software engineering drives our mission to protect the digital world..
        /// </summary>
        public static string TeamOneText {
            get {
                return ResourceManager.GetString("TeamOneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Davit Gasparyan.
        /// </summary>
        public static string TeamTwoName {
            get {
                return ResourceManager.GetString("TeamTwoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Developer.
        /// </summary>
        public static string TeamTwoState {
            get {
                return ResourceManager.GetString("TeamTwoState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Davit and Harutyun build the heart of our scanning tools. With a passion for AI and security, he ensures our platform is powerful and intuitive..
        /// </summary>
        public static string TeamTwoText {
            get {
                return ResourceManager.GetString("TeamTwoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram bot access with full website features.
        /// </summary>
        public static string TelegramBot {
            get {
                return ResourceManager.GetString("TelegramBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Security Hotspots.
        /// </summary>
        public static string TopSecurityHotspots {
            get {
                return ResourceManager.GetString("TopSecurityHotspots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted by Our Community.
        /// </summary>
        public static string Trusted {
            get {
                return ResourceManager.GetString("Trusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited scans for websites and files.
        /// </summary>
        public static string UnlimitedScans {
            get {
                return ResourceManager.GetString("UnlimitedScans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to Premium.
        /// </summary>
        public static string UpgradeToPremium {
            get {
                return ResourceManager.GetString("UpgradeToPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 3 file scans per day.
        /// </summary>
        public static string UpTo3File {
            get {
                return ResourceManager.GetString("UpTo3File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Trust.
        /// </summary>
        public static string UserTrust {
            get {
                return ResourceManager.GetString("UserTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified User.
        /// </summary>
        public static string VerifiedUser {
            get {
                return ResourceManager.GetString("VerifiedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View More.
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerabilities Detected.
        /// </summary>
        public static string VulnerabilitiesDetected {
            get {
                return ResourceManager.GetString("VulnerabilitiesDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vulnerabilities found.
        /// </summary>
        public static string VulnerabilitiesFound {
            get {
                return ResourceManager.GetString("VulnerabilitiesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerability Scanner.
        /// </summary>
        public static string VulnerabilityScanner {
            get {
                return ResourceManager.GetString("VulnerabilityScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Scans.
        /// </summary>
        public static string WebsiteScans {
            get {
                return ResourceManager.GetString("WebsiteScans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Websites Scanned.
        /// </summary>
        public static string WebsitesScanned {
            get {
                return ResourceManager.GetString("WebsitesScanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website URL.
        /// </summary>
        public static string WebsiteURL {
            get {
                return ResourceManager.GetString("WebsiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Drives Us.
        /// </summary>
        public static string WhatDrivesUs {
            get {
                return ResourceManager.GetString("WhatDrivesUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Choose ScanGuard.
        /// </summary>
        public static string WhyChooseScanGuard {
            get {
                return ResourceManager.GetString("WhyChooseScanGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        public static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a Review.
        /// </summary>
        public static string WriteaReview {
            get {
                return ResourceManager.GetString("WriteaReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your.
        /// </summary>
        public static string Your {
            get {
                return ResourceManager.GetString("Your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your  Email.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message.
        /// </summary>
        public static string YourMessage {
            get {
                return ResourceManager.GetString("YourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Security Advantage.
        /// </summary>
        public static string YourSecurityAdvantage {
            get {
                return ResourceManager.GetString("YourSecurityAdvantage", resourceCulture);
            }
        }
    }
}
